version: 2.1

parameters:
  branch:
    type: string
    default: ""
  sha:
    type: string
    default: ""
  pr_number:
    type: integer
    default: 0

jobs:
  setup:
    docker:
      - image: mattermost/mattermost-build-webapp:oct-2-2018
    working_directory: /go/src/github.com/metanerd/
    steps:
      - run:
          name: Checkout mattermost-server
          command: |
            mkdir -p ~/.ssh/
            echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            git clone git@github.com:mattermost/mattermost-server.git

            cd mattermost-server
            git checkout $CIRCLE_BRANCH || git checkout master
            git branch
      - run:
          name: Checkout mattermost-webapp
          command: |
            ls -la
            mkdir -p ~/.ssh/
            echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            git clone git@github.com:mattermost/mattermost-webapp.git

            cd mattermost-webapp
            git checkout $CIRCLE_BRANCH || git checkout master

            git branch
            export WEBAPP_GIT_COMMIT=$(git rev-parse HEAD)
            echo "$WEBAPP_GIT_COMMIT"

            curl -f -o ./dist.tar.gz https://pr-builds.mattermost.com/mattermost-webapp/commit/${WEBAPP_GIT_COMMIT}/mattermost-webapp.tar.gz && mkdir ./dist && tar -xvf ./dist.tar.gz -C ./dist --strip-components=1 || echo "curl failed" && export CURL_FAILED=1
            if [ $CURL_FAILED -eq 1 ]
            then
              npm ci && cd node_modules/mattermost-redux && npm install && npm run build && cd ../.. && make build
            fi
      - persist_to_workspace:
          root: /go/src/github.com/metanerd
          paths:
            - mattermost-server
            - mattermost-webapp

  build:
    docker:
      - image: mattermost/mattermost-build-server:oct-18-2019
    working_directory: /go/src/github.com/metanerd/circleci-ee
    steps:
      - checkout
      - attach_workspace:
          at: /go/src/github.com/metanerd/
      - run:
          command: |
            echo "Installing golangci-lint"
      - persist_to_workspace:
          root: /go/src/github.com/metanerd
          paths:
            - mattermost-server
            - mattermost-webapp

  test:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/go/src/github.com/metanerd/circleci-ee
    steps:
      - run: git branch

workflows:
  version: 2
  enterprise-build:
    jobs:
      - setup
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              ignore: /^pull\/.*$/
